NEWS_SOURCES = {
    "The Hindu": {
        "home": "https://www.thehindu.com/",
        "entertainment": "https://www.thehindu.com/entertainment/",
        "business": "https://www.thehindu.com/business/",
        "sports" : "https://www.thehindu.com/sport/",
        "world" : "https://www.thehindu.com/news/international/",
        "lifestyle" : "https://www.thehindu.com/life-and-style/",
        "technology" : "https://www.thehindu.com/sci-tech/technology/",


    },
    "NDTV": {
        "home": "https://www.ndtv.com/",
        "entertainment": "https://movies.ndtv.com/?pfrom=home-header-globalnav",
        "lifestyle": "https://swirlster.ndtv.com/?pfrom=home-header-globalnav",
        "technology": "https://gadgets.ndtv.com/?pfrom=home-header-globalnav",
        "business" : "https://www.ndtv.com/business",
        "sports" : "https://sports.ndtv.com/cricket?pfrom=home-header-globalnav",
        "world" : "https://www.ndtv.com/world-news?pfrom=home-mainnavgation"
    },
    "Times of India": {
        "home": "https://timesofindia.indiatimes.com/briefs",
        "entertainment": "https://timesofindia.indiatimes.com/briefs/entertainment",
        "business": "https://timesofindia.indiatimes.com/briefs/business",
        "sports" : "https://timesofindia.indiatimes.com/briefs/sports",
        "world" : "https://timesofindia.indiatimes.com/briefs/world",
        "lifestyle" : "https://timesofindia.indiatimes.com/briefs/lifestyle",
        "technology" : "https://timesofindia.indiatimes.com/briefs/gadgets",
    },
    "Hindustan Times": {
        "home": "https://www.hindustantimes.com/",
        "entertainment": "https://www.hindustantimes.com/entertainment/",
        "business": "https://www.hindustantimes.com/business-news/",
        "sports" : "https://www.hindustantimes.com/sports-news/",
        "world" : "https://www.hindustantimes.com/world-news/",
        "lifestyle" : "https://www.hindustantimes.com/lifestyle/",
        "technology" : "https://www.hindustantimes.com/science/",
    },
    "Deccan Chronicle": {
        "home": "https://www.deccanchronicle.com/",
        "entertainment": "https://www.deccanchronicle.com/entertainment",
        "business": "https://www.deccanchronicle.com/business",
        "sports" : "https://www.deccanchronicle.com/sports",
        "world" : "https://www.deccanchronicle.com/world",
        "lifestyle" : "https://www.deccanchronicle.com/lifestyle",
        "technology" : "https://www.deccanchronicle.com/technology",
    },
    "DD News": {
        "home": "http://ddnews.gov.in/",
        "entertainment": "http://ddnews.gov.in/entertainment",
        "business": "http://ddnews.gov.in/business",
        "sports" : "http://ddnews.gov.in/sports",
        "world" : "http://ddnews.gov.in/international",
        "lifestyle" : "http://ddnews.gov.in/health",
        "technology" : "http://ddnews.gov.in/sci-tech",
    },
    "NEWS18": {
        "home": "https://www.news18.com/",
        "entertainment": "https://www.news18.com/entertainment/",
        "business": "https://www.news18.com/business/",
        "sports" : "https://www.news18.com/sports/",
        "world" : "https://www.news18.com/world/",
        "lifestyle" : "https://www.news18.com/lifestyle/",
        "technology" : "https://www.news18.com/tech/",
    },
    "Telegraph": {
        "home": "https://www.telegraphindia.com/",
        "entertainment": "https://www.telegraphindia.com/entertainment",
        "business": "https://www.telegraphindia.com/business",
        "sports" : "https://www.telegraphindia.com/sports",
        "world" : "https://www.telegraphindia.com/world",
        "lifestyle" : "https://www.telegraphindia.com/health",
        "technology" : "https://www.telegraphindia.com/science-tech",
    },
}