NEWS_SOURCES = {
    "The Hindu": {
        "home": "https://www.thehindu.com/",
        "entertainment": "https://www.thehindu.com/entertainment/",
        "business": "https://www.thehindu.com/business/",
        "sports" : "https://www.thehindu.com/sport/",
        "world" : "https://www.thehindu.com/news/international/",
        "health" : "https://www.thehindu.com/life-and-style/",
        "technology" : "https://www.thehindu.com/sci-tech/technology/",


    },
    "NDTV": {
        "home": "https://www.ndtv.com/",
        "entertainment": "https://movies.ndtv.com/?pfrom=home-header-globalnav",
        "health": "https://swirlster.ndtv.com/?pfrom=home-header-globalnav",
        "technology": "https://gadgets.ndtv.com/?pfrom=home-header-globalnav",
        "business" : "https://www.ndtv.com/business",
        "sports" : "https://sports.ndtv.com/cricket?pfrom=home-header-globalnav",
        "world" : "https://www.ndtv.com/world-news?pfrom=home-mainnavgation"
    },
    "Times of India": {
        "home": "https://timesofindia.indiatimes.com/world/{}",
        "local": "https://timesofindia.indiatimes.com/india/{}",
        "entertainment": "https://timesofindia.indiatimes.com/briefs/entertainment/{}",
        "business": "https://timesofindia.indiatimes.com/briefs/business/{}",
        "sports" : "https://timesofindia.indiatimes.com/briefs/sports/{}",
        "world" : "https://timesofindia.indiatimes.com/briefs/world/{}",
        "health" : "https://timesofindia.indiatimes.com/briefs/lifestyle/{}",
        "technology" : "https://timesofindia.indiatimes.com/briefs/gadgets/{}",
    },
    "Hindustan Times": {
        "home": "https://www.hindustantimes.com/",
        "entertainment": "https://www.hindustantimes.com/entertainment/",
        "business": "https://www.hindustantimes.com/business-news/",
        "sports" : "https://www.hindustantimes.com/sports-news/",
        "world" : "https://www.hindustantimes.com/world-news/",
        "health" : "https://www.hindustantimes.com/lifestyle/",
        "technology" : "https://www.hindustantimes.com/science/",
    },
    "Deccan Chronicle": {
        "home": "https://www.deccanchronicle.com/",
        "entertainment": "https://www.deccanchronicle.com/entertainment",
        "business": "https://www.deccanchronicle.com/business",
        "sports" : "https://www.deccanchronicle.com/sports",
        "world" : "https://www.deccanchronicle.com/world",
        "health" : "https://www.deccanchronicle.com/lifestyle",
        "technology" : "https://www.deccanchronicle.com/technology",
    },
    "DD News": {
        "home": "http://ddnews.gov.in/",
        "local": "",
        "entertainment": "http://ddnews.gov.in/entertainment",
        "business": "http://ddnews.gov.in/business",
        "sports" : "http://ddnews.gov.in/sports",
        "world" : "http://ddnews.gov.in/international",
        "health" : "http://ddnews.gov.in/health",
        "technology" : "http://ddnews.gov.in/sci-tech",
    },
    "NEWS18": {
        "home": "https://www.news18.com/world/page-{}/",
        "local": "https://www.news18.com/india/page-{}/",
        "entertainment": "https://www.news18.com/entertainment/page-{}/",
        "business": "https://www.news18.com/business/page-{}/",
        "sports" : "https://www.news18.com/sports/page-{}/",
        "world" : "https://www.news18.com/world/page-{}/",
        "health" : "https://www.news18.com/lifestyle/health-and-fitness/page-{}/",
        "technology" : "https://www.news18.com/tech/page-{}/",
    },
    "Telegraph": {
        "home": "https://www.telegraphindia.com/",
        "entertainment": "https://www.telegraphindia.com/entertainment",
        "business": "https://www.telegraphindia.com/business",
        "sports" : "https://www.telegraphindia.com/sports",
        "world" : "https://www.telegraphindia.com/world",
        "health" : "https://www.telegraphindia.com/health",
        "technology" : "https://www.telegraphindia.com/science-tech",
    },
}